version: '3.3'

services:
  check_runner-api:
    build:
      dockerfile: Dockerfile
      context: ./
    image: cyjay96/check_runner-api
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: check_runner
    networks:
      - postgres-network
    restart: unless-stopped

  postgres:
    image: postgres:13.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: check_runner
    networks:
      - postgres-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - "./servers.json:/pgadmin4/servers.json"
    networks:
      - postgres-network
    restart: unless-stopped

networks:
  postgres-network:
